print("       A       ")
print("      A A      ")
print("     A   A     ")
print("    A     A    ")
print("   A A A A A   ")
print("  A         A  ")
print(" A           A ")
print("A             A")
